src/MiSitio/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views 
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.inicio, name='principal'),
    
    path('registro/', views.registro, name='registro'),

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/',auth_views.logout_then_login, name="logout"),

    path('Amigos/', include('apps.amigos.urls')),
    path('Dvd/', include('apps.dvd.urls')),




]

src/apps/amigos/urls.py
from django.urls import path 

from . import views

app_name = "amigos"

urlpatterns = [
	# path('Listar/', views.listar_amigos, name="listar"),
	path('Listar/', views.Listar.as_view(), name="listar"),
	# path('Nuevo/', views.nuevo_amigo, name="nuevo"),
	path('Nuevo/', views.CrearAmigo.as_view(), name="nuevo"),
	# path('Editar/<int:pk>/', views.editar_amigo, name="editar"),
	path('Editar/<int:pk>/', views.EditarAmigo.as_view(), name="editar")
] 

src/apps/dvd/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "dvd"

urlpatterns = [
	path('Listar/', views.Listar.as_view(), name="listar"),
	path('Nuevo/', views.CrearDvd.as_view(), name="nuevo"),
	path('Preguntar/', views.preguntar, name="preguntar"),

	# path('Jugar/Nivel/<int:nivel>/', views.Jugar, name="jugar"),
	# url(r'^Jugar/Nivel/(?P<nivel>[0-9]+)$')
]

src/apps/dvd/models.py
from django.db import models

ESTADO_CHOICES = (
	("A", "ACTIVO"),
	("I", "INACTIVO")
)

class Categoria(models.Model):
	nombre = models.CharField(max_length=255)

	class Meta:
		db_table = 'categorias'

	def __str__(self):
		return self.nombre

class Dvd(models.Model):
	nombre = models.CharField(max_length=255)
	fecha_compra = models.DateTimeField()
	cant_unidades = models.IntegerField(verbose_name='Cantidad de unidades')
	categorias = models.ManyToManyField(Categoria, related_name="categorias")	

	estado = models.CharField(max_length=1, choices=ESTADO_CHOICES, default="A")

	estado2 = models.BooleanField(default=True)

	class Meta:
		db_table = 'dvds'
		# verbose_name_plural='Dvdses'

	def __str__(self):
		return f"({self.id}) - {self.nombre}"
"""
class DvdCat(models.Model):
	categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
	dvd = models.ForeignKey(Dvd, on_delete=models.CASCADE)
"""

src/apps/dvd/forms.py
from django import forms

from .models import Dvd, ESTADO_CHOICES

class DvdForm(forms.ModelForm):
	nombre = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

	estado = forms.ChoiceField(choices=ESTADO_CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-check-input'}))

	estado2 = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
	
	class Meta:
		model = Dvd
		fields = ["nombre", "fecha_compra", "cant_unidades", "categorias", "estado", "estado2"]

class PreguntasForm(forms.Form):
	pregunta = forms.CharField(label="Responda la siguiente pregunta: ",widget=forms.TextInput(attrs={'class':'form-control'}))

	respuestas = forms.MultipleChoiceField(choices=[], widget=forms.CheckboxSelectMultiple)

	def __init__(self, pregunta, respuestas, *args, **kwargs):
	    super(PreguntasForm, self).__init__(*args, **kwargs)
	    self.fields["pregunta"].initial = pregunta
	    self.fields["pregunta"].widget.attrs["readonly"] = True

	    self.fields["respuestas"].choices = respuestas

class PreguntasForm2(forms.Form):
	def __init__(self, preguntas, *args, **kwargs):
	    super(PreguntasForm2, self).__init__(*args, **kwargs)
	    for i, p in enumerate(preguntas):
	    	nro_pregunta = i+1
	    	self.fields[f"pregunta_{nro_pregunta}"] = forms.CharField(label=f"Pregunta {nro_pregunta}", initial=p.descripcion)
	    	self.fields[f"pregunta_{nro_pregunta}"].widget.attrs["class"] = 'form-control'
	    	self.fields[f"pregunta_{nro_pregunta}"].widget.attrs["readonly"] = True

	    	self.fields[f"pregunta_opciones_{nro_pregunta}"] = forms.MultipleChoiceField(label="Seleccione una opcion", choices=[(r.id_resp, r.descripcion) for r in p.lista_respuestas], widget=forms.RadioSelect)

		

src/apps/dvd/views.py
from django.views.generic import ListView, CreateView
from django.shortcuts     import render
from django.urls          import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Dvd
from .forms  import DvdForm, PreguntasForm, PreguntasForm2


class Listar(LoginRequiredMixin, ListView):
	template_name = "dvd/listar.html"
	model = Dvd
	context_object_name = 'dvds'

	
	def get_queryset(self):
		#dvd = Dvd.objects.get(id=1)
		#print("==================")
		#for c in dvd.categorias.all():
		#	print(c)
		#print("==================")
		# x = Dvd.objects.filter(categorias__nombre="Infantil", es_admin=True)

		x = Dvd.objects.all()
		return x

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["es_administrador"] = False
		return context
	
class CrearDvd(CreateView):
	model = Dvd
	template_name = "dvd/crear.html"
	form_class = DvdForm 

	def get_success_url(self, **kwargs):
		return reverse_lazy("principal")

	def form_valid(self, form):
		"""
		f = form.save(commit=False)

		if f.estado == "I":
			pass
		"""
		return super(CrearDvd, self).form_valid(form)

# FormView
def preguntar2(request):
	template_name = "dvd/preguntar.html"

	ctx = {}

	if request.method == "POST":
		respuestas_marcadas = request.POST.getlist('respuestas')

		"""

		x = Amigo.objects.all().order_by("puntaje", "")   # [:10]
		if len(x) >= 10:
			x = Amigo.objects.all()[:10]
		else:
			x = Amigo.objects.all()[:len(x)]

		puntaje_total = 100


		request.user.puntaje = puntaje_total
		request.user.save()
		"""
		# string("asd")

		# return redirect("jugar:ver_respuesta")


	ctx["form"] = PreguntasForm(pregunta="¿Cual de los siguientes numeros son numeros pares?", respuestas=[(11, "44"),(12, "83"), (43, "91")])

	return render(request,template_name,ctx)

class Preg:
	def __init__(self, descripcion, lista_respuestas):
		self.descripcion=descripcion
		self.lista_respuestas=lista_respuestas

	def __str__(self):
		return self.descripcion
class Resp:
	def __init__(self, descripcion, es_correcta, id_resp):
		self.descripcion=descripcion
		self.es_correcta=es_correcta
		self.id_resp = id_resp




def preguntar(request):
	template_name = "dvd/preguntar.html"

	ctx = {}

	if request.method == "POST":
		# respuestas_marcadas = request.POST.getlist('respuestas')
		string("asd")
		#pass



	r11 = Resp(descripcion="asd", es_correcta=True, id_resp=1)
	r12 = Resp(descripcion="jjjjj", es_correcta=False, id_resp=2)
	r13 = Resp(descripcion="hhhhh", es_correcta=False, id_resp=3)
	x = [r11, r12, r13]
	
	p1 = Preg(descripcion="¿Como te va con tu proyecto final del info?", lista_respuestas=x)


	r21 = Resp(descripcion="gggg", es_correcta=True, id_resp=1)
	r22 = Resp(descripcion="dda", es_correcta=False, id_resp=2)
	r23 = Resp(descripcion="erq", es_correcta=False, id_resp=3)
	x = [r21, r22, r23]
	
	p2 = Preg(descripcion="¿Estas entendiendo como funcionan los formularios?", lista_respuestas=x)

	ctx["form"] = PreguntasForm2(preguntas=[p1, p2])

	return render(request,template_name,ctx)

src/templates/dvd/crear.html
{% extends "base/base.html" %}

{% block contenido %}
	<div class="album py-5 bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col">
    				<h1>NUEVO DVD</h1>
    			</div>
    		</div>

    		<div class="row">
    			
    			<div class="col">
    				<div class="bd-example">
	    				<form method="POST">{% csrf_token %}
	    					{% include "includes/_form_errors.html" with formulario=form %}

	    					<div class="mb-3">
	    						<label class="form-label">{{form.nombre.label}}</label>
	    						{{form.nombre}}
	    					</div>

	    					<div class="mb-3">
	    						<label class="form-label">{{form.fecha_compra.label}}</label>
	    						{{form.fecha_compra}}
	    					</div>
	    					<div class="mb-3">
	    						<label class="form-label">{{form.cant_unidades.label}}</label>
	    						{{form.cant_unidades}}
	    					</div>
	    					<div class="mb-3">
	    						<label class="form-label">{{form.categorias.label}}</label>
	    						{{form.categorias}}
	    					</div>

	    					<!--
	    					<div class="form-check">
	    						<label class="form-check-label">{{form.estado.label}}</label>
	    						{{form.estado}}
	    					</div>
							-->
	    					<div class="form-check-inline">
	    						<label class="form-check-label">{{form.estado2}} {{form.estado2.label}}</label>
	    						
	    					</div>
	    					<br><br><br>
	    					<button type="submit" class="btn btn-primary">Guardar</button>
	    					<a class="btn btn-danger" href="{% url 'amigos:listar' %}">Cancelar</a>
	    				</form>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
{% endblock contenido %}

src/templates/dvd/listar.html
{% extends "base/base.html" %}

{% block contenido %}
	<div class="album py-5 bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col">
    				<h1>Lista de Dvd</h1>
    			</div>
    		</div>

    		<div class="row">
      			<div class="col">
      				<h1> Mostrando un boolean</h1>
      				{% if es_administrador %}
      					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
  <path d="M13.485 1.431a1.473 1.473 0 0 1 2.104 2.062l-7.84 9.801a1.473 1.473 0 0 1-2.12.04L.431 8.138a1.473 1.473 0 0 1 2.084-2.083l4.111 4.112 6.82-8.69a.486.486 0 0 1 .04-.045z"/>
</svg>
      				{% else %}
      					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-circle" viewBox="0 0 16 16">
  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
  <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
</svg>
      					
      				{% endif %}
      			</div>
      		</div>
      		<div class="row">
      			<div class="col">
      				<table class="table">
					  <thead>
					    <tr>
					      <th scope="col">Nombre</th>
					      <th scope="col">Fecha de Compra</th>
					      <th scope="col">Cantidad de Unidades</th>
					      <th>Categorias</th>
					    </tr>
					  </thead>
					  <tbody>
					  	{% for dvd in dvds %}
						    <tr>
						      <td>{{dvd.nombre}}</td>
						      <td>{{dvd.fecha_compra}}</td>
						      <td>{{dvd.cant_unidades}}</td>
						      <td>
						      	{% for c in dvd.categorias.all  %}
						      		<span class="badge badge-primary">{{c.nombre}}</span>
						      	{% endfor %}
						      </td>
						    </tr>
						{% empty %}
							<tr>
								<td>No se encontraron resultados</td>
							</tr>
					    {% endfor %}
					  </tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock contenido %}

src/templates/dvd/preguntar.html
{% extends "base/base.html" %}

{% block css_extras %}    
	<style type="text/css">
		
		.bd-example {
		    padding: 1.5rem;
		    margin-right: 0;
		    margin-left: 0;
		    border-width: 1px;
		    border-top-left-radius: .25rem;
		    border-top-right-radius: .25rem;
		}



	</style>
{% endblock css_extras %}
{% block contenido %}
	<div class="album py-5 bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col">
    				<h1>Preguntas</h1>
    			</div>
    		</div>

    		<div class="row">
    			
    			<div class="col">
    				<div class="bd-example">
	    				<form method="POST">{% csrf_token %}
	    					{% include "includes/_form_errors.html" with formulario=form %}
	    					{% include "includes/_forms.html" with formulario=form %}

	    					<button type="submit" class="btn btn-primary">Guardar</button>
	    					<a class="btn btn-danger" href="{% url 'amigos:listar' %}">Cancelar</a>
	    				</form>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
{% endblock contenido %}