src/MiSitio/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views 
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.inicio, name='principal'),
    
    path('registro/', views.registro, name='registro'),

    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/',auth_views.logout_then_login, name="logout"),

    path('Amigos/', include('apps.amigos.urls')),
    path('Dvd/', include('apps.dvd.urls')),




]

src/apps/amigos/urls.py
from django.urls import path 

from . import views

app_name = "amigos"

urlpatterns = [
	# path('Listar/', views.listar_amigos, name="listar"),
	path('Listar/', views.Listar.as_view(), name="listar"),
	# path('Nuevo/', views.nuevo_amigo, name="nuevo"),
	path('Nuevo/', views.CrearAmigo.as_view(), name="nuevo"),
	# path('Editar/<int:pk>/', views.editar_amigo, name="editar"),
	path('Editar/<int:pk>/', views.EditarAmigo.as_view(), name="editar")
] 

src/apps/amigos/models.py
from django.db import models

class Amigo(models.Model):
	nombre = models.CharField(max_length=255)
	domicilio = models.CharField(max_length=255)
	apellido = models.CharField(max_length=255, null=True, blank=True)


	class Meta:
		db_table = 'amigos'

	def __str__(self):
		return self.nombre


CEL_CHOICES = (
	("0", "--"),
	("15", "15")
)

class Telefono(models.Model):
	amigo = models.ForeignKey(Amigo, on_delete=models.CASCADE)
	codigo_area = models.CharField(max_length=4)
	codigo_celular = models.CharField(max_length=2, choices=CEL_CHOICES)
	numero = models.CharField(max_length=15)

	class Meta:
		db_table = 'telefonos'

	def __str__(self):
		if self.codigo_celular == "15":
			return f"({self.codigo_area}) - {self.codigo_celular} {self.numero}"

		return f"({self.codigo_area}) - {self.numero}"

src/apps/amigos/forms.py
from django import forms

from .models import Amigo

class AmigoForm(forms.ModelForm):
	nombre = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	domicilio = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	apellido = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	class Meta:
		model = Amigo
		fields = ["nombre", "domicilio", "apellido"]

	def clean_nombre(self):
		nombre = self.cleaned_data["nombre"]

		if len(nombre)<3:
			self.add_error("nombre", "La longitud del nombre deber ser mayor a 3")

		return nombre

src/apps/amigos/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView
from django.views.generic.edit import UpdateView 
from django.urls import reverse_lazy

from .models import Amigo
from .forms  import AmigoForm
"""
@login_required
def listar_amigos(request):
	template_name="amigos/listar.html"
	
	lista_de_amigos = Amigo.objects.filter(nombre='Lucas')
	
	ctx={
		'amigos': lista_de_amigos
	}
	return render(request,template_name, ctx )


def nuevo_amigo(request):
	template_name="amigos/nuevo.html"

	if request.method == "POST":
		nombre = request.POST.get("nombre", None)
		domicilio = request.POST.get("domicilio", None)
		apellido = request.POST.get("apellido", None)
		a = Amigo.objects.create(nombre=nombre, apellido=apellido, domicilio=domicilio)

		return redirect('amigos:listar')

	ctx={
		'form': AmigoForm()
	}
	return render(request,template_name, ctx )


def editar_amigo(request, pk):
	template_name="amigos/editar.html"
	ctx = {
		'amigo': Amigo.objects.get(id=pk)
	}
	return render(request,template_name, ctx )

"""

class EditarAmigo(UpdateView):
	model = Amigo
	template_name = "amigos/editar.html"
	form_class = AmigoForm 

	def get_success_url(self, **kwargs):
		return reverse_lazy("amigos:listar")

class CrearAmigo(CreateView):
	model = Amigo
	template_name = "amigos/nuevo.html"
	form_class = AmigoForm 

	def get_success_url(self, **kwargs):
		return reverse_lazy("amigos:listar")

class Listar(LoginRequiredMixin, ListView):
	template_name = "amigos/listar.html"
	model = Amigo
	context_object_name = 'amigos'

	
	def get_queryset(self):
		"""
		a = Amigo.objects.get(id=1)
		a = Amigo.objects.filter(nombre = "lucas", id=1).order_by('id').last()
		for x in a:
			print(x)
		"""
		if self.request.user.is_superuser:
			return Amigo.objects.all()

		return Amigo.objects.filter(nombre="Lucas")
	

	"""
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["color"] = "amarillo"
		return context
	"""

"""
def Jugar(request, nivel):
	if nivel == 1:
		cant_preg = 10
	...
	return render ...
"""

src/templates/amigos/editar.html
{% extends "base/base.html" %}

{% block contenido %}
	<div class="album py-5 bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col">
    				<h1>Editar amigo: {{amigo.nombre}} {{amigo.apellido}}</h1>
    			</div>
    		</div>

    		<div class="row">
    			<div class="col">
    				<form method="POST">{% csrf_token %}
    					{{form.as_p}}

    					 <button type="submit" class="btn btn-primary">Guardar</button>
    					 <a class="btn btn-danger" href="{% url 'amigos:listar' %}">Cancelar</a>
    				</form>
    			</div>
    		</div>
    	</div>
    </div>
{% endblock contenido %}

src/templates/amigos/listar.html
{% extends "base/base.html" %}

{% block contenido %}
	<div class="album py-5 bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col">
    				<h1>Lista de amigos</h1>
    			</div>
    		</div>

    		<div class="row" style="padding:10px;">
    			<div class="col">
    				<a href="{% url 'amigos:nuevo' %}" class="btn btn-success" style="float:right;">Nuevo Amigo</a>
				</div>
    		</div>
      		<div class="row">
      			<div class="col">
      				<table class="table">
					  <thead>
					    <tr>
					      <th scope="col">Nombre</th>
					      <th scope="col">Apellido</th>
					      <th scope="col">Direccion</th>
					      <th></th>
					    </tr>
					  </thead>
					  <tbody>
					  	{% for a in amigos %}
						    <tr>
						      <td>{{a.nombre}}</td>
						      <td>{{a.apellido|default:'-'}}</td>
						      <td>{{a.domicilio}}</td>
						      <td>
						      	<a href="{% url 'amigos:editar' a.pk %}">Editar</a>
						      </td>
						    </tr>
						{% empty %}
							<tr>
								<td>No se encontraron resultados</td>
							</tr>
					    {% endfor %}
					  </tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock contenido %}

src/templates/amigos/nuevo.html
{% extends "base/base.html" %}

{% block css_extras %}    
	<style type="text/css">
		
		.bd-example {
		    padding: 1.5rem;
		    margin-right: 0;
		    margin-left: 0;
		    border-width: 1px;
		    border-top-left-radius: .25rem;
		    border-top-right-radius: .25rem;
		}



	</style>
{% endblock css_extras %}
{% block contenido %}
	<div class="album py-5 bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="col">
    				<h1>Crear amigo</h1>
    			</div>
    		</div>

    		<div class="row">
    			
    			<div class="col">
    				<div class="bd-example">
	    				<form method="POST">{% csrf_token %}
	    					{% include "includes/_form_errors.html" with formulario=form %}
	    					{% include "includes/_forms.html" with formulario=form %}

	    					<button type="submit" class="btn btn-primary">Guardar</button>
	    					<a class="btn btn-danger" href="{% url 'amigos:listar' %}">Cancelar</a>
	    				</form>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
{% endblock contenido %}